### ISSUE TITLE
OAuth Sandbox URL undocumented

### ISSUE THREAD

**Issue by flow-danny** [bunq/doc#116]
https://oauth.sandbox.bunq.com/auth

I believe this used to work. Did the OAuth sandbox URL change?

---

Also, this URL is undocumented.

**Comment by lexym** [comment]
@flow-danny must be fixed now. Let me know if it's working for you.

**Comment by lexym** [comment]
Added the following to the docs:
OAuth URL: https://oauth.sandbox.bunq.com/auth  (for authorization)
OAuth URL: https://api-oauth.sandbox.bunq.com/v1/token (for token exchange)
