### ISSUE TITLE
ShareInviteBankResponse.relation_user is missing from the OpenAPI definition

### ISSUE THREAD

**Issue by NilsTellow** [bunq/doc#147]
The OpenAPI definition does not mention the `relation_user` property of a `ShareInviteBankResponse` object.

**Comment by angelomelonas** [comment]
Hi @NilsTellow 👋🏼 

Thank you for creating this issue 🙏🏼  We are aware of this and it will be resolved soon (when the docs are updated to match the latest SDK release).

**Comment by angelomelonas** [comment]
Hi @NilsTellow. I am just informing you that the latest [docs](https://github.com/bunq/doc/releases/tag/1.14.1) have been released.
