### ISSUE TITLE
Quick Start page instructions look really bad

### ISSUE THREAD

**Issue by jleclanche** [bunq/doc#152]
Example:
https://developer.bunq.com/en/quick-starts/getting-started-with-python

![image](https://user-images.githubusercontent.com/235410/84593968-7bbf3780-ae4f-11ea-9a8d-90825f8d5080.png)

The code snippets are centered, not syntax-highlighted, and preceded with a `$`. This is only appropriate for the very first shell command.

Even just this would look a lot better:

![image](https://user-images.githubusercontent.com/235410/84594066-f9834300-ae4f-11ea-86c9-a03a24e61cca.png)

**Comment by jleclanche** [comment]
These snippets should really include the matching bunq_sdk imports as well.

**Comment by lexym** [comment]
Fixed! Thanks for reporting this @jleclanche!
