### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by tlrh314** [bunq/doc#164]
Dead link in c58e3fb9b7e5dba75f3ee1e494036e33a2a3d26b #72
 
https://doc.bunq.com/, section `IP addresses`:

> IP addresses
>
> When using a standard API Key the DeviceServer and Installation that are created in this process are bound to the IP address they are created from. Afterwards it is only possible to add IP addresses via the Permitted IP endpoint.
>
> Using a Wildcard API Key gives you the freedom to make API calls from any IP address after the POST device-server. You can switch to a Wildcard API Key by tapping on “Allow All IP Addresses” in your API Key menu inside the bunq app. You can also programatically switch to a Wildcard API Key by passing your current ip and a * (asterisk) in the permitted_ips field of the device-server POST call. E.g: ["1.2.3.4", "*"].
>
> Find out more at this link https://bunq.com/en/apikey-dynamic-ip.

```bash
curl -I https://www.bunq.com/en/apikey-dynamic-ip
HTTP/2 404
date: Mon, 17 Aug 2020 13:52:54 GMT
content-type: text/html; charset=UTF-8
cache-control: no-cache, must-revalidate
pragma: no-cache
expires: Mon, 17 Aug 2020 12:52:54 GMT
set-cookie: CRAFT_CSRF_TOKEN=24eaa74eaec650b372ee1366e4c14647221539f96b51c432b7608eeca6e8dfdaa%3A2%3A%7Bi%3A0%3Bs%3A16%3A%22CRAFT_CSRF_TOKEN%22%3Bi%3A1%3Bs%3A40%3A%22BnBzSUpsvp5xQDu5CsE3-SRLJYjqQsb2MteEwvGI%22%3B%7D; path=/; secure; HttpOnly
strict-transport-security: max-age=31536000
x-content-type-options: nosniff
x-frame-options: sameorigin
age: 0
x-cache: MISS
x-cache-hits: 0
x-cache-grace: none
x-domain-powered-by: bunq.com
```

**Comment by lexym** [comment]
this will be included into the next doc build
