### ISSUE TITLE
Service workers

### ISSUE THREAD

**Issue by Crecket** [bunq/doc#21]
I was thinking it'd be nice to add a service worker to the new documentation page which could significantly speed up the loading time for the new documentation. And since the service worker works in the background it wouldn't require some kind of rewrite in the theme/template that is currently used.

If you want I can create a pull request to set this up using something like [sw-precahe](https://github.com/GoogleChromeLabs/sw-precache) which is Google's library to easily create a service worker script. 

The trade-off then becomes that new versions of the documentation won't be visible instantly since a cached version will be shown first but you would have sub 1 second/near instant load times

**Comment by Crecket** [comment]
Lazy loading is definitely the best solution 👍

Setting up a proper service worker will probably take an hour to set it up and test if everything is loaded/cached correctly. Especially if you use the sw-precache/sw-toolbox projects from Google which are just simple scripts which you can run to generate it

**Comment by OGKevin** [comment]
@Crecket if thats the case then i would say goahead and create a PR. Ill discuss this internally as well to doublecheck if this is compliant but i have a feeling it is :)

**Comment by OGKevin** [comment]
@Crecket BTW, please follow this contribution [guide](https://raw.githubusercontent.com/bunq/sdk_php/develop/.github/PULL_REQUEST_TEMPLATE.md)
