### ISSUE TITLE
Can't view the first chapters before "amount-used"

### ISSUE THREAD

**Issue by chiel87** [bunq/doc#50]
Can't see anything before the "amount-used" chapter. Tested on different browsers and devices.

**Comment by OGKevin** [comment]
yup, seems that the tool we are using now cant handle the doc. I'm aware of this and am looking into it. 

For now, you can use http://petstore.swagger.io/ and use bunq.com/swagger.json to view the documentation.

**Comment by bwesterb** [comment]
![screen shot 2018-07-29 at 17 02 29](https://user-images.githubusercontent.com/9975/43367680-354e1f70-9351-11e8-9a86-182527e1cf17.png)

**Comment by OGKevin** [comment]
Using the url it redirect to Should fix cross errors. In this case, it redircts to  https://raw.githubusercontent.com/bunq/doc/master/swagger.json 
		
		

		Outlook voor iOS downloaden

**Comment by OGKevin** [comment]
closing this in favour of #56
