### ISSUE TITLE
monetary-account-joint endpoint is missing

### ISSUE THREAD

**Issue by basst85** [bunq/doc#64]
## Steps to reproduce:
1. Go to https://doc.bunq.com/#/monetary-account-joint

## What should happen:
1. Show information about the monetary-account-joint endpoint 

## What happens:
1. It doesn't show the information

**Comment by OGKevin** [comment]
Eh, someone forgot to add it to the allowed public endpoints 🤦‍♂️ 

This also means its not in the SDK's neither 😭

Do you need it now for the hackethon or can this wait ?

**Comment by basst85** [comment]
Unfortunately I'm not @ the bunq hackathon, so I think this can wait?

But check this topic: https://together.bunq.com/d/4137-api-doesn-t-return-cj-shared-account

**Comment by lucasilverentand** [comment]
Hey, I have an app that is supposed to go into the app store next week but this causing some problems. Have there been any updates on this?

**Comment by kojoru** [comment]
Fixed in #70.
