### ISSUE TITLE
Document how to permit a wildcard IP on device-server

### ISSUE THREAD

**Issue by wvteijlingen** [bunq/doc#71]
According to [this thread on together](https://together.bunq.com/d/4660-api-how-to-permit-all-ip-addresses-when-posting-a-device-server) you can add a wildcard IP to a device-server by using a `*`.

> (...) it is possible to create a wildcard key if you populate the permitted_ips with the current IP you're making calls from and * to also add wildcard.

This information is critical when you're dealing with dynamic IPs (which is most of the time I think). Therefore I think this information should be added to the documentation.

**Comment by OGKevin** [comment]
@wvteijlingen thanks for reporting. As this is a simple text addition, feel free to create a PR adding this to DESCRIPTION.MD.

**Comment by wvteijlingen** [comment]
https://github.com/bunq/doc/pull/72
