### ISSUE TITLE
Update Doc to improve usability

### ISSUE THREAD

**Issue by parrello** [bunq/doc#75]
Doc has been moved to Swagger, but it still needs some work to improve it.

The following is required:
* [x] Add a sidebar with links to all topics and endpoints
* [x] Remove hashes from model names
* [x] Add a mapping between pre-Swagger doc urls and new ones

**Comment by basst85** [comment]
@parrello The new menu is visible on a desktop, and it looks/works nice 👍🏻

But the menu is not very responsive, on a tablet i get a half menu and on my phone no menu.

**Comment by parrello** [comment]
@basst85 thanks! I've been working on fixes for the last day and will probably release them today. Right now the menu is not visible by design on a phone, as the bunq update didn't really leave a lot of time for this and as mobile browsing is not the main use case when looking up API docs :)

If you have any suggestion/remark just let me know, as with everything there's always something to improve!

**Comment by OGKevin** [comment]
> and as mobile browsing is not the main use case when looking up API docs :)

you would be supprised xD :P

**Comment by parrello** [comment]
@OGKevin interesting. Why do you think it's the case?

**Comment by OGKevin** [comment]
I know this guy 😂 who likes to use his Ipad Pro as a "second screen" and bc its touchscreen navigating documentation was easier on there and he didn't have to keep switching windows on his MacBook. 

But ofc its, not a widely used use case 😁  but seeing that @basst85 brought this up this guy I'm referring to is not the only one.

Ok wait now that I reread your sentence its indeed not the Main use case, but you would be surprised how many actually do use a tablet for docs, that's more what I meant to say.

**Comment by parrello** [comment]
@OGKevin maybe I was not clear, but my question was limited to browsing from a *phone*. Tablets (will soon) work fine, and to be fair the iPad pro is almost  bigger than my laptop screen, so responsiveness is not an issue there :)
