### ISSUE TITLE
Improve doc: not clear if is possible to exchange real money between two accounts using the api

### ISSUE THREAD

**Issue by Iar0** [bunq/doc#87]
Reading through https://doc.bunq.com/, I don't get if is possible to exchange **real** money between two accounts using the api.

The [OAuth Section](https://doc.bunq.com/#/oauth) says, under the "What can my apps do with OAuth?" section:
- Create new Payments, but only between Monetary Accounts belonging to the same user.

So, probably, this means that I cannot create an app on top of the api where an user give his permission, so then he can simply tap a button and the app can get money from his bank account right?

What I think I can do, based on the [Payment Request Section](https://doc.bunq.com/#/quickstart-payment-request), is to ask the user to make a payment each time he taps the button. In this way he can select his preferred way of payment (through ideal, for example). Is this right?

Can you please confirm my assumptions? Thanks for your time 👍

**Comment by OGKevin** [comment]
I don't understand, you can make payments with the API? Just use the `/payment` endpoint?

**Comment by Iar0** [comment]
@OGKevin I'm asking if, on top of the API or SDK, is possible to build an app where:
- the user can give permission (just once) to get money from his account OR
- every time the user need to pay, the app can give a payment request for the user

I want to create an app where users can buy items and I'm trying to figure out if I can do that through bunq

**Comment by Iar0** [comment]
since this is more a clarification than a real issue I'm closing it, I think I can build what I want using the SDKs or API directly.

Thanks!
